// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgr1zgrs6jkENQKz9KtC9v4PRqOquk0Tg',
    appId: '1:707694973433:web:900b49e53da03091996d28',
    messagingSenderId: '707694973433',
    projectId: 'ubixstar-a438a',
    authDomain: 'ubixstar-a438a.firebaseapp.com',
    storageBucket: 'ubixstar-a438a.appspot.com',
    measurementId: 'G-HBWB7LQ1QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdW0UHqrhgjvnTERqh4k1GgQ9lk1TbXhQ',
    appId: '1:707694973433:android:ec059676c29a3c3d996d28',
    messagingSenderId: '707694973433',
    projectId: 'ubixstar-a438a',
    storageBucket: 'ubixstar-a438a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhBq2Vkp9odXtKWDEzH0rDP_3yxlTdej0',
    appId: '1:707694973433:ios:1fe7072a41ef1bc6996d28',
    messagingSenderId: '707694973433',
    projectId: 'ubixstar-a438a',
    storageBucket: 'ubixstar-a438a.appspot.com',
    iosBundleId: 'com.example.ubixstar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhBq2Vkp9odXtKWDEzH0rDP_3yxlTdej0',
    appId: '1:707694973433:ios:a3f3c71f5d51c39c996d28',
    messagingSenderId: '707694973433',
    projectId: 'ubixstar-a438a',
    storageBucket: 'ubixstar-a438a.appspot.com',
    iosBundleId: 'com.example.ubixstar.RunnerTests',
  );
}
